# Generated by Django 5.0.1 on 2024-01-21 12:00

import CometWeb.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='movie_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster', models.FileField(upload_to='movieposter/')),
                ('moviefile', models.FileField(upload_to='moviefile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), CometWeb.models.validate_file_extension])),
                ('year', models.PositiveIntegerField()),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CometWeb.movie_genres')),
            ],
        ),
    ]
