# Generated by Django 5.0.1 on 2024-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CometWeb', '0002_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'all_searches',
            },
        ),
    ]
