# Generated by Django 5.0.1 on 2024-01-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CometWeb', '0003_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_genres',
            name='background',
            field=models.ImageField(default=True, upload_to='genrebackground/'),
            preserve_default=False,
        ),
    ]
